// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "bootstrap"
import "fontawesome"
import "amcharts"
import "apexcharts"
import "chartjs"
import "apexchart"
import "amchart"
// import "datatable"
// import "datepicker"
// import "echart"
// import "editor"
// import "fullcalender"
// import "jvectormap"
// import "multistep"
// import "sweetalert"
import "main"